// demo/vue/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="select-philippines-address demo"/>
    <select @change="handleProvince">
      <option disabled selected>Select Region</option>
      <option v-for="region in regions" :value="region.region_code" :key="region.region_code">{{
          region.region_name
        }}
      </option>
    </select>
    <br/><br/>
    <select @change="handleCity">
      <option disabled selected>Select Province</option>
      <option v-for="province in provinces" :value="province.province_code" :key="province.province_code">
        {{ province.province_name }}
      </option>
    </select>
    <br/><br/>
    <select @change="handleBarangay">
      <option disabled selected>Select City</option>
      <option v-for="city in cities" :value="city.city_code" :key="city.city_code">{{ city.city_name }}</option>
    </select>
    <br/><br/>
    <select @change="barangaysChange">
      <option disabled selected>Select Barangay</option>
      <option v-for="barangay in barangays" :value="barangay.brgy_code" :key="barangay.brgy_code">{{
          barangay.brgy_name
        }}
      </option>
    </select>
    <br/><br/>
    <p>{{ barangay }}, {{ city }}, {{ province }}, {{ region }}</p>
    <br/>
    <a href="https://github.com/isaacdarcilla/select-philippines-address">select-philippines-address by Isaac</a>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
// eslint-disable-next-line no-unused-vars
import {regions, provinces, cities, barangays} from 'select-philippines-address';

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data() {
    return {
      regions: [],
      provinces: [],
      cities: [],
      barangays: [],
      region: null,
      province: null,
      city: null,
      barangay: null,
    }
  },
  created() {
    regions().then(response => {
      this.regions = response;
    });
  },
  methods: {
    handleProvince(e) {
      this.region = e.target.selectedOptions[0].text;
      provinces(e.target.value).then(response => {
        this.provinces = response;
      });
    },
    handleCity(e) {
      this.province = e.target.selectedOptions[0].text;
      cities(e.target.value).then(response => {
        this.cities = response;
      });
    },
    handleBarangay(e) {
      this.city = e.target.selectedOptions[0].text;
      barangays(e.target.value).then(response => {
        this.barangays = response;
      });
    },
    barangaysChange(e) {
      this.barangay = e.target.selectedOptions[0].text;
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// demo/react/src/App.js
import './App.css';
import {regions, provinces, cities, barangays} from 'select-philippines-address';
import {useEffect, useState} from "react";

const App = () => {
    const [regionData, setRegion] = useState([]);
    const [provinceData, setProvince] = useState([]);
    const [cityData, setCity] = useState([]);
    const [barangayData, setBarangay] = useState([]);

    const [regionAddr, setRegionAddr] = useState("");
    const [provinceAddr, setProvinceAddr] = useState("");
    const [cityAddr, setCityAddr] = useState("");
    const [barangayAddr, setBarangayAddr] = useState("");

    const region = () => {
        regions().then(response => {
            setRegion(response);
        });
    }

    const province = (e) => {
        setRegionAddr(e.target.selectedOptions[0].text);
        provinces(e.target.value).then(response => {
            setProvince(response);
            setCity([]);
            setBarangay([]);
        });
    }

    const city = (e) => {
        setProvinceAddr(e.target.selectedOptions[0].text);
        cities(e.target.value).then(response => {
            setCity(response);
        });
    }

    const barangay = (e) => {
        setCityAddr(e.target.selectedOptions[0].text);
        barangays(e.target.value).then(response => {
            setBarangay(response);
        });
    }

    const brgy = (e) => {
        setBarangayAddr(e.target.selectedOptions[0].text);
    }

    useEffect(() => {
        region()
    }, [])

    return (
        <div className="App">
            <header className="App-header">
                <h1>REACT JS</h1>
                <h4>select-philippines-address demo</h4>
                <select onChange={province} onSelect={region}>
                    <option disabled>Select Region</option>
                    {
                        regionData && regionData.length > 0 && regionData.map((item) => <option
                            key={item.region_code} value={item.region_code}>{item.region_name}</option>)
                    }
                </select><br/>
                <select onChange={city}>
                    <option disabled>Select Province</option>
                    {
                        provinceData && provinceData.length > 0 && provinceData.map((item) => <option
                            key={item.province_code} value={item.province_code}>{item.province_name}</option>)
                    }
                </select><br/>
                <select onChange={barangay}>
                    <option disabled>Select City</option>
                    {
                        cityData && cityData.length > 0 && cityData.map((item) => <option
                            key={item.city_code} value={item.city_code}>{item.city_name}</option>)
                    }
                </select><br/>
                <select onChange={brgy}>
                    <option disabled>Select Barangay</option>
                    {
                        barangayData && barangayData.length > 0 && barangayData.map((item) => <option
                            key={item.brgy_code} value={item.brgy_code}>{item.brgy_name}</option>)
                    }
                </select>
                <p>Address</p>
                 {barangayAddr}, {cityAddr}, {provinceAddr}, {regionAddr}
            </header>
        </div>
    );
}

export default App;
